language: cpp

env:
  global:
    - MAKEFLAGS="-j 4"
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

install:

# Install cpp-coveralls if build-type is Debug
  - if [ "$BUILD_TYPE" = "Debug" ]; then
      sudo pip install cpp-coveralls;
      export CXX_FLAGS='--coverage -O0';
      export EXE_LINKER_FLAGS='--coverage';
    fi

before_script:
  - cmake --version
  - gcc --version

script:
  - mkdir build
  - cd build
  - cmake
    -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    -DCMAKE_CXX_FLAGS=$CXX_FLAGS
    -DCMAKE_EXE_LINKER_FLAGS=$EXE_LINKER_FLAGS
    ..
  - make
  - ctest

after_failure:
  - cat Testing/Temporary/LastTest.log

after_success:
  - coveralls --root .. --gcov-options '\-lp' --include include > /dev/null 2>&1
